# Generated by Django 3.2 on 2021-04-28 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be more than 8 character', regex='^[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}$')], verbose_name='bank account'),
        ),
    ]
