# Generated by Django 3.2 on 2021-05-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210428_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [['customer', 'is customer']]},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [['supplier', 'is supplier']]},
        ),
    ]
