# Generated by Django 3.2 on 2021-05-05 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210503_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
